// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Group struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	GroupType   *GroupType `json:"group_type"`
}

type GroupType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Item struct {
	Value string `json:"value"`
	Group *Group `json:"group"`
}

type NewGroup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	GroupTypeID string `json:"group_type_id"`
}

type NewItem struct {
	Value   string `json:"value"`
	GroupID string `json:"group_id"`
}
